server.port=${SERVER_PORT:18082}
spring.datasource.url=${DB_URL:jdbc:mysql://127.0.0.1:3306/flydb_demo}
spring.datasource.username=${DB_USER:root}
spring.datasource.password=${DB_PASSWORD:test}
spring.datasource.hikari.maximum-pool-size=2

flydb.database-type=mysql
flydb.locations=classpath:db/migration
flydb.table=flydb_boot2_history
